#!/bin/bash

FC=ifort
FLAGS=""

#Uncomment to see the backtrace generated by the executable compiled with gfortran
#FC=gfortran  



$FC -c $FLAGS -o mod_three.o mod_three.f90
$FC -c $FLAGS -o mod_two.o mod_two.f90
$FC -c $FLAGS -o mod_one.o mod_one.f90
$FC -c $FLAGS -o main.o main.f90
$FC $FLAGS -o main mod_three.o main.o mod_two.o mod_one.o

